### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by feliciathemilkyway** [AzureCosmosDB/gallery#20]
The repo for Build a Copilot App in Pythin with Azure Comos DB for NoSQL does not exist: https://github.com/microsoft/azuredataretrievalaugmentedgenerationsamples/blob/main/python/cosmosdb-nosql_vectorsearch/cosmosdb-nosql-quickstart-rag-chatbot.ipynb
 
 
![missing repo](https://github.com/user-attachments/assets/4a6de9b0-4f98-4941-8385-35d78155da93)

**Comment by markjbrown** [comment]
@sajeetharan the templates.json URL is correct. Something is lower casing the URL on that page.

**Comment by sajeetharan** [comment]
@markjbrown  fixed
