### ISSUE TITLE
Change the readme

### ISSUE THREAD

**Issue by feliciathemilkyway** [AzureCosmosDB/gallery#21]
This one is about bikes but talks about lakes: https://github.com/azurecosmosdb/cosmosdb-nosql-copilot

**Comment by markjbrown** [comment]
Fixed that repo. Thanks @feliciathemilkyway for reporting.

**Comment by feliciathemilkyway** [comment]
[heart]         Felicia Lobillo Vilela reacted to your message:
________________________________
